pathways:
  default: workshop

  paths:
    workshop:
      title: "Workshop"

      steps:
      - 00-workshop-overview
      - 01-first-steps
      - 02-next-upgrade-steps
      - 03-spring-boot-upgrades
      - 04-final-upgrades
      - 05-continous-upgrades
      - 99-workshop-summary
